/*
===============================================================================
Script: Market Share & Part-to-Whole Analysis
Project: E-commerce Exploratory Data Analysis (EDA)
Description: 
    This script calculates the relative contribution of each subcategory 
    to the total company revenue. It identifies the "Hero" subcategories 
    that drive the majority of the business.
===============================================================================
*/

-- 1. TOP CONTRIBUTING SUBCATEGORIES (MARKET SHARE)
-- Question: Which 5 subcategories represent the largest share of our total sales?

WITH subcategory_sales AS (
    SELECT 
        p.subcategory,
        SUM(f.sales_amount) AS sales_by_subcategory
    FROM fact f
    JOIN products p ON f.product_key = p.product_key
    GROUP BY p.subcategory
)
SELECT
    subcategory,
    sales_by_subcategory,
    -- Window Function: SUM() OVER() calculates the Grand Total across all rows
    SUM(sales_by_subcategory) OVER() AS grand_total_sales,
    
    -- Part-to-Whole Calculation (Cast to numeric for decimal precision)
    ROUND(
        (sales_by_subcategory::numeric / SUM(sales_by_subcategory) OVER()) * 100, 
        2
    ) || '%' AS market_share_pct
FROM subcategory_sales
ORDER BY (sales_by_subcategory::numeric / SUM(sales_by_subcategory) OVER()) DESC
LIMIT 5;

-- 2. GENDER-BASED REVENUE CONTRIBUTION
-- Question: What percentage of our total revenue is generated by each gender?

SELECT 
    c.gender,
    SUM(f.sales_amount) AS revenue_by_gender,
    ROUND(
        (SUM(f.sales_amount)::numeric / SUM(SUM(f.sales_amount)) OVER()) * 100, 
        2
    ) || '%' AS revenue_share_pct
FROM fact f
JOIN customers c ON f.customer_key = c.customer_key
GROUP BY c.gender;